package main

// GENERATED FILE - DO NOT MODIFY BY HAND.
// (generated by /home/dgv/go/src/cmd/godoc/setup-godoc-app.bash)

const (
	// .zip filename
	zipFilename = "godoc.zip"

	// goroot directory in .zip file
	zipGoroot = "/pt_BR"

	// glob pattern describing search index files
	// (if empty, the index is built at run-time)
	indexFilenames = "index.split.*"
)
